# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-09 09:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlTeacherEx', models.CharField(max_length=500)),
                ('urlStudentEx', models.CharField(max_length=500)),
            ],
        ),
        migrations.RenameModel(
            old_name='Exercise',
            new_name='TeacherExercise',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='urlExcercise',
            new_name='urlTeacherEx',
        ),
    ]
