# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-15 12:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0002_auto_20151209_0945'),
    ]

    operations = [
        migrations.CreateModel(
            name='FichJs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('urlstudent', models.CharField(max_length=500)),
                ('name', models.CharField(max_length=500)),
                ('content', models.TextField()),
            ],
        ),
    ]
