# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 16:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0004_auto_20151217_1614'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichjs',
            name='analisis',
        ),
    ]
