# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0005_remove_fichjs_analisis'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichjs',
            name='resultado',
            field=models.CharField(default='', max_length=500),
        ),
    ]
