# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0006_fichjs_resultado'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichjs',
            name='resultado',
        ),
        migrations.AddField(
            model_name='fichjs',
            name='analisis',
            field=models.CharField(default='', max_length=50000),
        ),
    ]
