# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2015-12-17 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0007_auto_20151217_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fichjs',
            name='analisis',
            field=models.TextField(),
        ),
    ]
