# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 17:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0008_auto_20151217_1714'),
    ]

    operations = [
        migrations.CreateModel(
            name='Error',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student', models.CharField(max_length=500)),
                ('typeoferror', models.CharField(max_length=500)),
                ('description', models.TextField()),
            ],
        ),
    ]
