# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-03 18:47
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0009_error'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='fich',
            field=models.CharField(default=datetime.datetime(2016, 2, 3, 18, 47, 31, 356380, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
