# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 09:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0010_error_fich'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichjs',
            name='optional',
            field=models.BooleanField(default=False),
        ),
    ]
