# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0012_error_exercise'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='fichjs',
            name='optional',
        ),
    ]
