# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-04 18:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0013_remove_fichjs_optional'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='solution',
            field=models.CharField(default=datetime.datetime(2016, 2, 4, 18, 35, 14, 808321, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
