# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 12:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0015_auto_20160209_1102'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichjs',
            name='sumary',
            field=models.CharField(default=datetime.datetime(2016, 2, 9, 12, 30, 24, 531332, tzinfo=utc), max_length=15000),
            preserve_default=False,
        ),
    ]
