# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-09 16:51
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0017_auto_20160209_1232'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='sumary',
            field=models.TextField(default=datetime.datetime(2016, 2, 9, 16, 51, 24, 157984, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
