# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 15:32
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0018_studentexercise_sumary'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexercise',
            name='porcentaje',
            field=models.CharField(default=datetime.datetime(2016, 2, 10, 15, 32, 17, 702234, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
