# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-10 15:59
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0019_teacherexercise_porcentaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexercise',
            name='sumary',
            field=models.TextField(default=datetime.datetime(2016, 2, 10, 15, 59, 2, 791558, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
