# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 10:58
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0020_teacherexercise_sumary'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='numportfolio',
            field=models.CharField(default=datetime.datetime(2016, 2, 15, 10, 58, 15, 191511, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
