# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 15:52
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0021_studentexercise_numportfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichjs',
            name='exercise',
            field=models.CharField(default=datetime.datetime(2016, 2, 15, 15, 52, 11, 609639, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
