# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-15 17:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0022_fichjs_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='nofichfind',
            field=models.BooleanField(default=False),
        ),
    ]
