# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 13:35
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0023_studentexercise_nofichfind'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='numzindex',
            field=models.CharField(default=datetime.datetime(2016, 2, 16, 13, 35, 12, 154538, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
