# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-16 13:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0024_studentexercise_numzindex'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentexercise',
            name='numzindex',
        ),
    ]
