# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-17 18:22
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0027_studentexercise_urlavatar'),
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('errors', models.CharField(max_length=500)),
            ],
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='numfichanaliz',
            field=models.CharField(default=datetime.datetime(2016, 2, 17, 18, 22, 41, 757234, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
