# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 12:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0028_auto_20160217_1822'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='teacherexercise',
            name='porcentaje',
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='porcenterrorsfich',
            field=models.CharField(default=datetime.datetime(2016, 2, 18, 12, 12, 54, 932132, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingtotal',
            field=models.TextField(default=datetime.datetime(2016, 2, 18, 12, 13, 10, 916917, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
