# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-18 15:56
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0030_delete_student'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingfich',
            field=models.TextField(default=datetime.datetime(2016, 2, 18, 15, 56, 49, 234168, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
