# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-24 17:25
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0031_teacherexercise_rankingfich'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='line',
            field=models.CharField(default=datetime.datetime(2016, 2, 24, 17, 25, 11, 945443, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
