# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-25 18:30
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0032_error_line'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexercise',
            name='data',
            field=models.CharField(default=datetime.datetime(2016, 2, 25, 18, 30, 12, 396326, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
