# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 10:36
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0033_teacherexercise_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichjs',
            name='data',
            field=models.CharField(default=datetime.datetime(2016, 2, 29, 10, 36, 18, 903387, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
