# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-02-29 16:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0034_fichjs_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='firstfich',
            field=models.CharField(default=datetime.datetime(2016, 2, 29, 16, 5, 36, 695294, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
