# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 10:34
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0036_studentexercise_hayfirstfich'),
    ]

    operations = [
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingerrors',
            field=models.TextField(default=datetime.datetime(2016, 3, 2, 10, 34, 8, 135032, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
