# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-02 18:54
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0037_teacherexercise_rankingerrors'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='branch',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 18, 54, 22, 955223, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichjs',
            name='branch',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 18, 54, 34, 484166, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='branch',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 18, 54, 39, 788529, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='branch',
            field=models.CharField(default=datetime.datetime(2016, 3, 2, 18, 54, 44, 980847, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
