# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 09:50
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0038_auto_20160302_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='tool',
            field=models.CharField(default=datetime.datetime(2016, 3, 8, 9, 50, 15, 138156, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
