# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 18:41
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0039_error_tool'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichjs',
            old_name='data',
            new_name='dataJSHint',
        ),
        migrations.RenameField(
            model_name='fichjs',
            old_name='sumary',
            new_name='sumaryJSHint',
        ),
        migrations.AddField(
            model_name='fichjs',
            name='dataJSLint',
            field=models.CharField(default=datetime.datetime(2016, 3, 8, 18, 41, 44, 91737, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichjs',
            name='sumaryJSLint',
            field=models.TextField(default=datetime.datetime(2016, 3, 8, 18, 41, 51, 652692, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
