# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-08 19:13
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0040_auto_20160308_1841'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichjs',
            old_name='analisis',
            new_name='analisisJSHint',
        ),
        migrations.AddField(
            model_name='fichjs',
            name='analisisJSLint',
            field=models.TextField(default=datetime.datetime(2016, 3, 8, 19, 13, 13, 778478, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
