# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 11:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0041_auto_20160308_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexercise',
            old_name='porcenterrorsfich',
            new_name='porcenterrorsfichJSHint',
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='porcenterrorsfichJSLint',
            field=models.CharField(default=datetime.datetime(2016, 3, 9, 11, 40, 20, 787029, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
