# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-09 13:05
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0042_auto_20160309_1140'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='data',
            new_name='dataJSHint',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingerrors',
            new_name='rankingerrorsJSHint',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingfich',
            new_name='rankingerrorsJSLint',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingtotal',
            new_name='rankingfichJSHint',
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='dataJSLint',
            field=models.CharField(default=datetime.datetime(2016, 3, 9, 13, 5, 35, 716423, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingfichJSLint',
            field=models.TextField(default=datetime.datetime(2016, 3, 9, 13, 5, 41, 732149, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingpercentJSHint',
            field=models.TextField(default=datetime.datetime(2016, 3, 9, 13, 5, 48, 316787, tzinfo=utc)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='rankingpercentJSLint',
            field=models.TextField(default=datetime.datetime(2016, 3, 9, 13, 5, 55, 372837, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
