# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 11:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0043_auto_20160309_1305'),
    ]

    operations = [
        migrations.RenameField(
            model_name='fichjs',
            old_name='dataJSHint',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='fichjs',
            old_name='sumaryJSHint',
            new_name='sumary',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='dataJSHint',
            new_name='data',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingerrorsJSHint',
            new_name='rankingerrors',
        ),
        migrations.RemoveField(
            model_name='fichjs',
            name='dataJSLint',
        ),
        migrations.RemoveField(
            model_name='fichjs',
            name='sumaryJSLint',
        ),
        migrations.RemoveField(
            model_name='teacherexercise',
            name='dataJSLint',
        ),
        migrations.RemoveField(
            model_name='teacherexercise',
            name='rankingerrorsJSLint',
        ),
    ]
