# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-10 16:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0044_auto_20160310_1137'),
    ]

    operations = [
        migrations.RenameField(
            model_name='studentexercise',
            old_name='porcenterrorsfichJSHint',
            new_name='porcenterrorsfich',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingfichJSHint',
            new_name='rankingfich',
        ),
        migrations.RenameField(
            model_name='teacherexercise',
            old_name='rankingfichJSLint',
            new_name='rankingpercent',
        ),
        migrations.RemoveField(
            model_name='studentexercise',
            name='porcenterrorsfichJSLint',
        ),
        migrations.RemoveField(
            model_name='teacherexercise',
            name='rankingpercentJSHint',
        ),
        migrations.RemoveField(
            model_name='teacherexercise',
            name='rankingpercentJSLint',
        ),
    ]
