# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-18 09:01
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0046_library'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 9, 1, 15, 397142, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='fichjs',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 9, 1, 21, 493578, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='library',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 9, 1, 26, 733937, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 9, 1, 31, 918203, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='user',
            field=models.CharField(default=datetime.datetime(2016, 3, 18, 9, 1, 37, 302484, tzinfo=utc), max_length=500),
            preserve_default=False,
        ),
    ]
