# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 10:43
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.utils.timezone
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0048_auto_20160321_1244'),
    ]

    operations = [
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user', models.CharField(max_length=500)),
                ('rankingerrors', models.TextField()),
                ('data', models.CharField(max_length=10000)),
            ],
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='numoferrors',
            field=models.CharField(default=django.utils.timezone.now, max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='numoferrors',
            field=models.CharField(default=datetime.datetime(2016, 3, 22, 10, 43, 32, 252243, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
