# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-22 15:40
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0049_auto_20160322_1043'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='datafich',
            field=models.CharField(default=datetime.datetime(2016, 3, 22, 15, 40, 7, 200179, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
