# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 12:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0051_studentexercise_divdata'),
    ]

    operations = [
        migrations.AddField(
            model_name='error',
            name='numorden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='fichjs',
            name='numorden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='islast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='studentexercise',
            name='numorden',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='islast',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='numorden',
            field=models.IntegerField(default=0),
        ),
    ]
