# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-03-23 17:08
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('checkexercises', '0052_auto_20160323_1209'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentexercise',
            name='datacomparar',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 17, 8, 30, 826289, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='teacherexercise',
            name='datacomparar',
            field=models.CharField(default=datetime.datetime(2016, 3, 23, 17, 8, 37, 602463, tzinfo=utc), max_length=10000),
            preserve_default=False,
        ),
    ]
